"""add attachment fields

Revision ID: 7de01e896802
Revises: e3b317f4bfa9
Create Date: 2025-12-21 21:08:22.986362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de01e896802'
down_revision = 'e3b317f4bfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_mime', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_mime')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
